### ISSUE TITLE
Doesn't run outside of normal mode

### ISSUE THREAD

**Issue by nordmagnus999** [rickhowe/partialnumber.vim#1]
Before saying anything: Great work! took me a while to find this gem.

And so the problem i notice (though minor) is that it doesn't seem to update the line number, if i either delete a line or make a empty newline *when* I'm outside normal mode.

If i quit insert mode and go to normal mode, it seems to update the count correctly.
Don't think it would be a good idea to ask this on the SE post since it would be unrelated (since it work and it's only a minor inconveniences).

**Comment by rickhowe** [comment]
Thanks.  If you are using later than 8.1.1320, the numbers are synchronously  updated even in the insert mode since this plugin uses the new function, listener_add(). The latest neovim does not yet support the function though.

**Comment by nordmagnus999** [comment]
Closing this since it's resolved with latest compiled Vim :).
